plugins {
    id 'com.android.application'
}

android {
    namespace 'com.retro.shenzhou'
    compileSdk 34

    defaultConfig {
        applicationId "com.retro.shenzhou"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        ndk {
            // 适配主流手机架构
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
